### ISSUE TITLE
[1.12.2] Absorption is broken.

### ISSUE THREAD

**Issue by Z-Tunic** [Jackiecrazy/ArmorCurve#1]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 2
armorcurve-1.2.0-hotfix
jei_1.12.2-4.15.0.291

=====

Any damage that you take will affect BOTH absorb & health, with or without armor. Tested this while taking fall damage, cactus damage, mob damage, etc. Absorb is suppose to go first if you have any before health gets affected.

*Note*
I know that this is outside the scope of this mod but still giving it a mention. While this is unintended as absorb is suppose to go first before affecting your health when taking damage... I wonder if that could have some use if one could put in damage sources that bypasses absorb and instead affects health directly. For example...

'drown' / 'cactus' / 'magic' damage sources... if put in the 'damage that bypasses absorb' config... will ignore absorb and instead affect health directly if you take damage from those sources... but other sources such as 'mob' / 'arrow' / etc. will damage absorb first and then damage health when you have no absorb.

Might also be a way to make half of the damage taken affect both absorb & health, if one takes 10 damage but has 20 absorb & 20 health... 5 of the damage will affect absorb while 5 of the damage will effect health. Of course... after all damage reduction calculations have been made & such.

**Comment by Jackiecrazy** [comment]
ouch, yeah... minecraft's a little stupid while handling absorption hearts, I'll get to fixing that. As for the second one, that's a little out of the scope of this mod, but maybe I can justify adding it in NoDamItem. I might add a config option for damage to affect absorption differently, now that you mention it, but damage sources affecting variable amounts of absorption and health is a little unnecessarily complicated considering the ~2 hearts of absorption you usually get.

**Comment by Z-Tunic** [comment]
True, a mod like Natural Absorption came to mind as your absorb acts like a shield that regens if you avoid taking damage & figure if the damage could split between absorb & health... but if it's complicated, it's alright.

**Comment by Jackiecrazy** [comment]
closed last night.
