### ISSUE TITLE
[Suggestion] % Damage Reduction for each Armor Point

### ISSUE THREAD

**Issue by Xarmat-GitHub** [Jackiecrazy/ArmorCurve#3]
Add an linear calculation option into the config that allows % based reduction while ignoring all vanilla behaviour.
At the moment (as far I test it) the higher the damage, the less worth is armor protection and things get wired.

Example:
Config: 1 Armor Point = 2% reduction

In Game:
5 Armor -> 10% deduction 
10 A -> 20%
20 A -> 40%
40 A -> 80%
50 A -> 100% (no damage income)

Opportunity's:
- No wired Vanilla formula (When Damage is more then X -> then your armor perform X% less then usual)
- Modpack Makers will know there range of max armor points the player can get in there modpack and can balance this value as needed - same with the armor parts and there armor points

Example from my Modpack (WIP):
- Cloth Armor - 20% dmg reduction | can perform elctroblobs magic and skills | mage play style
- Light Armor - 40% dmg reduction | stealth, mobs can only see you while facing in your direction + gab closer skill | assassin playstyle
- Medium Armor - 60% dmg reduction | slow backwards movement | fighter play style
- Heavy Armor - 80% dmg reduction | slow movement | tank play style

Optional:
- Create a new Mod and don't integrate it in this one

**Comment by Xarmat-GitHub** [comment]
Hint: When Armor Toughness has a high value (lest say 999), then the system works like in the description above.
Allowing 4% reduction for each Armor Point wearing.

**Comment by Jackiecrazy** [comment]
I suppose this is 1.12? Active development is no longer continuing on that branch.

**Comment by Xarmat-GitHub** [comment]
Oh, then this ticket can be closed.
Ty for the feedback 👍
