### ISSUE TITLE
Invalid mixins declaration in v2.2

### ISSUE THREAD

**Issue by Ephys** [Jackiecrazy/ArmorCurve#4]
Hi :)

Your latest release (https://www.curseforge.com/minecraft/mc-mods/armor-curve/files/3221211) incorrectly declares `MixinConfigs: wardance.mixins.json` in its MANIFEST.MF, instead of `MixinConfigs: armorcurve.mixins.json`

Edit: fixing it then crashes with `org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: com.udojava.evalex.Expression` during mixin evaluation

**Comment by Jackiecrazy** [comment]
oops! Fixed.
